name: mnist-cnn-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - pip
  - numpy
  - matplotlib
  - scikit-learn
  - seaborn
  - cudnn=9.1
  - pip:
      - tensorflow[and-cuda]