name: mnist-cnn-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - pip
  - numpy=1.25.2
  - matplotlib
  - scikit-learn
  - seaborn
  - cudatoolkit
  - cudnn=8.9
  - pip:
      - tensorflow==2.15
